http:
  middlewares:
    traefik-auth:
      basicAuth:
        usersFile: /run/secrets/traefik_basicauth
    traefik-redir:
      redirectRegex:
        regex: "^https?://([^/]+)/?$"
        replacement: "https://${1}/dashboard/"
        permanent: true

  routers:
    traefik-api:
      entryPoints: [websecure]
      middlewares: [traefik-auth]
      rule: Host(`traefik.hexwyrm.com`) && PathPrefix(`/api`)
      service: api@internal
      tls: {}

    traefik-root:
      entryPoints: [websecure]
      middlewares: [traefik-auth, traefik-redir]
      rule: Host(`traefik.hexwyrm.com`) && Path(`/`)
      service: noop@internal
      tls: {}

    traefik-ui:
      entryPoints: [websecure]
      middlewares: [traefik-auth]
      rule: Host(`traefik.hexwyrm.com`) && PathPrefix(`/dashboard`)
      service: api@internal
      tls: {}
