http:
  routers:
    traefik-ui:
      rule: Host(`traefik.hexwyrm.com`) && PathPrefix(`/dashboard`)
      entryPoints: [websecure]
      tls: true
      service: dashboard@internal
      middlewares: [traefik-auth]

    traefik-api:
      rule: Host(`traefik.hexwyrm.com`) && PathPrefix(`/api`)
      entryPoints: [websecure]
      tls: true
      service: api@internal
      middlewares: [traefik-auth]

    traefik-root:
      rule: Host(`traefik.hexwyrm.com`) && Path(`/`)
      entryPoints: [websecure]
      tls: true
      service: noop@internal
      middlewares: [traefik-auth, traefik-redir]

  middlewares:
    traefik-auth:
      basicAuth:
        usersFile: /run/secrets/traefik_basicauth

    traefik-redir:
      redirectRegex:
        regex: "^https?://([^/]+)/?$"
        replacement: "https://${1}/dashboard/"
        permanent: true
