# Cloudflared locally-managed tunnel
tunnel: c1a27dbd-9770-4ac2-98e2-643080c1a243
credentials-file: /etc/cloudflared/c1a27dbd-9770-4ac2-98e2-643080c1a243.json

originRequest:
  connectTimeout: 30s

ingress:
  - hostname: portainer.hexwyrm.com
    service: https://edge-traefik:443
    originRequest:
      httpHostHeader: portainer.hexwyrm.com

  - hostname: traefik.hexwyrm.com
    service: https://edge-traefik:443
    originRequest:
      httpHostHeader: traefik.hexwyrm.com

  - hostname: whoami.hexwyrm.com
    service: https://edge-traefik:443
    originRequest:
      httpHostHeader: whoami.hexwyrm.com

  # Catch-all (must be last)
  - service: http_status:404

