services:
  edge-traefik:
    env_file:
      - /opt/dragoncave/secrets/cloudflare.env
    command:
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.disablePropagationCheck=true
    volumes:
      - /opt/dragoncave/data/letsencrypt/acme.json:/letsencrypt/acme.json
    labels:
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
      - traefik.http.routers.traefik.tls.domains[0].main=hexwyrm.com
      - traefik.http.routers.traefik.tls.domains[0].sans=*.hexwyrm.com
