services:
  edge-traefik:
    image: traefik:v3.1
    container_name: edge-traefik
    command:
      - --api.dashboard=true
      - --log.level=DEBUG
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      # ACME via Cloudflare DNS-01
      - --certificatesresolvers.cloudflare.acme.email=admin@hexwyrm.com
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.cloudflare.acme.keytype=RSA4096
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=1m
    env_file:
      - /opt/dragoncave/secrets/cloudflare.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/dragoncave/configs/traefik:/etc/traefik/dynamic:ro
      - /opt/dragoncave/data/letsencrypt:/letsencrypt
      - /opt/dragoncave/secrets/traefik_basicauth.htpasswd:/run/secrets/traefik_basicauth:ro
    restart: unless-stopped
