services:
  portainer:
    image: portainer/portainer-ce:latest
    user: "0:0"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=edge"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      # Proxy awareness headers
      - "traefik.http.middlewares.portainer-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.portainer-headers.headers.customrequestheaders.X-Forwarded-Host=portainer.${PUBLIC_DOMAIN}"
      - "traefik.http.middlewares.portainer-headers.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.routers.portainer.middlewares=portainer-headers@docker"

networks:
  edge:
    external: true

volumes:
  portainer_data:
    external: true
    name: stacks_portainer_data
