services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - edge
    environment:
      - TZ=Africa/Johannesburg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=edge"
      - "traefik.http.routers.portainer.rule=Host(`portainer.hexwyrm.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"
      - "traefik.http.services.portainer.loadbalancer.server.scheme=https"
      - "traefik.http.services.portainer.loadbalancer.passhostheader=true"

networks:
  edge:
    external: true
