services:
  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    networks:
      - core
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "0 0 3 * * *"
      WATCHTOWER_LABEL_ENABLE: "true"
      DOCKER_HOST: tcp://dprox:2375
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

networks:
  core:
    external: true
