services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    user: "0:0"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - edge
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - /opt/dragoncave/configs/cloudflared:/etc/cloudflared:ro
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  edge:
    external: true
