services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks: [edge]
    command: tunnel --no-autoupdate run --token /run/secrets/CF_TUNNEL_TOKEN
    healthcheck:
      test: ["CMD", "cloudflared", "version"]
      interval: 60s
      timeout: 5s
      retries: 5
    secrets:
      - CF_TUNNEL_TOKEN

secrets:
  CF_TUNNEL_TOKEN:
    file: /opt/dragoncave/secrets/CF_TUNNEL_TOKEN

networks:
  edge:
    external: true
