name: Preflight Diagnostics

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  preflight:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install lint dependencies
        env:
          HADOLINT_VERSION: "2.12.0"
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck yamllint
          curl -sSL \
            "https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64" \
            -o hadolint
          sudo install -m 0755 hadolint /usr/local/bin/hadolint
          rm -f hadolint

      - name: Run preflight diagnostics
        run: make preflight
